### ISSUE TITLE
Item progress bars are using a wrong color

### ISSUE THREAD

**Issue by Sepitus-exe** [wrex/ed-themer#1]
Looks like the progress bars under individual items present on dash are still using brand color.
That's no longer the case for the theme. It should be the progress color instead.

![image](https://user-images.githubusercontent.com/82216846/221249215-78645bc1-2a75-4d1b-9afc-a33134b06141.png)
![image](https://user-images.githubusercontent.com/82216846/221250900-0f6eb8ee-9e52-42f7-9a41-a64fbc6ceb11.png)

**Comment by wrex** [comment]
Nice catch. Thanks.

Fix pushed to main, site should rebuild shortly.
